services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: "kafka-cluster-kafkade-01"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - kafka-network

  signal_simulator:
    build:
      context: ./signal_simulator
      dockerfile: Dockerfile
    container_name: signal_simulator
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: signals
      MESSAGE_INTERVAL: 1
    networks:
      - kafka-network

  mail_simulator:
    build:
      context: ./mail_simulator
      dockerfile: Dockerfile
    container_name: mail_simulator
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: mails
      MESSAGE_INTERVAL: 2
      DRY_RUN: "false"
    networks:
      - kafka-network

  mail_formatter:
    build:
      context: ./mail_formatter
      dockerfile: Dockerfile
    container_name: mail_formatter
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_INPUT_TOPIC: mails
      KAFKA_OUTPUT_TOPIC: tickets_formatted
      KAFKA_DLQ_TOPIC: mail_dlq
      KAFKA_GROUP_ID: mail-formatter-group
    networks:
      - kafka-network

  signal_consumer:
    build:
      context: ./signal_consumer
      dockerfile: Dockerfile
    container_name: signal_consumer
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      INPUT_KAFKA_TOPIC: signals
      OUTPUT_KAFKA_TOPIC: tickets_formatted
    networks:
      - kafka-network

  
  ticket_labeller:
    build:
      context: ./ticket-labeller
      dockerfile: Dockerfile
    container_name: ticket_labeller
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    networks:
      - kafka-network

volumes:
  kafka_data:
    driver: local

networks:
   kafka-network:
      driver: bridge
